version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:your-password@db.your-project-id.supabase.co:5432/postgres
      - FIREBASE_ADMIN_SDK_PATH=./firebase-admin-sdk.json
    volumes:
      - .:/app